from graph import *
from node import  *

g = Graph()
g.add_node(Node("A", 1, 20))
g.add_node(Node("A", 2, 5)) #prueba para ver que no se puden registrar nodos con el mismo nombre
g.add_node(Node("tata", 1, 20)) #Prueba para ver que no se pueden registrar nodos que estan en la misma posicion
g.add_node(Node("B", 8, 17))
g.add_node(Node("C", 15, 20))
g.add_node(Node("D", 18, 15))
g.add_node(Node("E", 2, 4))
g.add_node(Node("F", 6, 5))
g.add_node(Node("G", 12, 12))
g.add_node(Node("H", 10, 3))
g.add_node(Node("I", 19, 1))
g.add_node(Node("J", 13, 5))
g.add_node(Node("K", 3, 15))
g.add_node(Node("L", 4, 10))
g.add_segment("FL", "F", "L")
g.add_segment("AB", "A", "B")
g.add_segment("AB", "A", "B") #prueba para ver que no se pueden registrar segmentos con el mismo nombre
g.add_segment("Patatas", "A", "B") #ni segmentos con el mismo origen y destino
g.add_segment("AE", "A", "E")
g.add_segment("AK", "A", "K")
g.add_segment("BA", "B", "A")
g.add_segment("BC", "B", "C")
g.add_segment("BF", "B", "F")
g.add_segment("BK", "B", "K")
g.add_segment("BG", "B", "G")
g.add_segment("CD", "C", "D")
g.add_segment("CG", "C", "G")
g.add_segment("DG", "D", "G")
g.add_segment("DH", "D", "H")
g.add_segment("DI", "D", "I")
g.add_segment("EF", "E", "F")
g.add_segment("FL", "F", "L")
g.add_segment("GB", "G", "B")
g.add_segment("GF", "G", "F")
g.add_segment("GH", "G", "H")
g.add_segment("ID", "I", "D")
g.add_segment("IJ", "I", "J")
g.add_segment("JI", "J", "I")
g.add_segment("KA", "K", "A")
g.add_segment("KL", "K", "L")
g.add_segment("LK", "L", "K")
g.add_segment("LF", "L", "F")
#g.info_segmentos()
#g.info_nodo('A')
#g.info_nodo('J')
#g.info_nodo('F')
#g.load_flight_plan('guardado1')
#g.plot(True)
#g.plot_node('C', True)
#g.find_shortest_path('F', 'E')

#g.save_flight_plan('prueba.txt')
#g.load_flight_plan('prueba.txt')
print("Probando el grafo...")


